include: "/views/raw/v_llm_response.view.lkml"

view: +v_llm_response {
  sql_table_name: `@{PROJECT_ID}.@{DATASET_NAME}.v_llm_response` ;;

  dimension: pk {
    primary_key: yes
    hidden: yes
    type: string
    sql: CONCAT(${trace_id}, '|', ${span_id}) ;;
    description: "Internal composite primary key for symmetric aggregates."
  }

  dimension: usage_total_tokens {
    group_label: "Token Usage"
    description: "The total number of tokens (prompt + completion) consumed by this specific LLM response."
  }

  dimension: usage_prompt_tokens {
    group_label: "Token Usage"
    description: "The number of tokens consumed by the input prompt sent to the LLM."
  }

  dimension: usage_completion_tokens {
    group_label: "Token Usage"
    description: "The number of tokens consumed by the output generated by the LLM."
  }

  dimension: usage_cached_tokens {
    group_label: "Token Usage"
    description: "The number of prompt tokens that were served from the context cache, reducing latency and cost."
  }

  dimension: context_cache_hit_rate {
    group_label: "Token Usage"
    description: "The percentage of the prompt that was served from the cache (cached tokens / total prompt tokens)."
  }

  dimension: total_ms {
    group_label: "Latency"
    description: "The total wall-clock time in milliseconds the LLM took to process the request and generate the full response."
  }

  dimension: ttft_ms {
    group_label: "Latency"
    description: "Time To First Token (TTFT). The latency in milliseconds before the LLM began streaming the first token of the response."
  }

  dimension: model_version {
    group_label: "Event Info"
    description: "The specific version of the LLM model used for this request (e.g., 'gemini-2.5-flash')."
  }

  # --- BASE MEASURES ---

  measure: total_tokens_consumed {
    group_label: "Usage & Volume"
    type: sum
    sql: ${usage_total_tokens} ;;
    description: "Total tokens consumed across all LLM responses in the selected timeframe."
    drill_fields: [agent_events.timestamp_time, agent_events.agent, agent_events.user_id, agent_events.trace_id, model_version, total_ms]
    
    link: {
      label: "Show Tokens Over Time (Area Chart)"
      url: "@{VIZ_AREA_CHART}{{ link }}&fields=agent_events.timestamp_date,{{ _view._name }}.total_tokens_consumed&fill_fields=agent_events.timestamp_date&sorts=agent_events.timestamp_date+desc&limit=500&column_limit=50&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
    link: {
      label: "Top 5 Agents (for this selection)"
      url: "@{VIZ_BAR_CHART}{{ link }}&fields={{ _view._name }}.total_tokens_consumed,agent_events.agent&sorts={{ _view._name }}.total_tokens_consumed+desc&limit=5&column_limit=50&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
    link: {
      label: "Top 5 Users (for this selection)"
      url: "@{VIZ_BAR_CHART}{{ link }}&fields={{ _view._name }}.total_tokens_consumed,agent_events.user_id&sorts={{ _view._name }}.total_tokens_consumed+desc&limit=5&column_limit=50&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
  }

  measure: total_prompt_tokens {
    group_label: "Usage & Volume"
    type: sum
    sql: ${usage_prompt_tokens} ;;
    description: "Total prompt tokens consumed across all LLM responses."
    drill_fields: [agent_events.timestamp_time, agent_events.agent, agent_events.user_id, agent_events.trace_id, model_version, total_ms]
  }

  measure: total_completion_tokens {
    group_label: "Usage & Volume"
    type: sum
    sql: ${usage_completion_tokens} ;;
    description: "Total completion (candidate) tokens generated across all LLM responses."
    drill_fields: [agent_events.timestamp_time, agent_events.agent, agent_events.user_id, agent_events.trace_id, model_version, total_ms]
  }

  measure: total_llm_calls {
    group_label: "Usage & Volume"
    type: count
    description: "Total number of successful LLM responses."
    drill_fields: [agent_events.timestamp_time, agent_events.agent, agent_events.user_id, agent_events.trace_id, model_version, total_ms]
  }

  measure: average_llm_latency {
    group_label: "Performance & Reliability"
    type: average
    sql: ${total_ms} ;;
    description: "Average latency for LLM responses in milliseconds."
    value_format_name: decimal_1
  }

  measure: p50_llm_latency {
    group_label: "Performance & Reliability"
    type: percentile
    percentile: 50
    sql: ${total_ms} ;;
    description: "Median (P50) latency for LLM responses in milliseconds."
  }

  measure: p75_llm_latency {
    group_label: "Performance & Reliability"
    type: percentile
    percentile: 75
    sql: ${total_ms} ;;
    description: "75th percentile latency for LLM responses in milliseconds."
  }

  measure: p90_llm_latency {
    group_label: "Performance & Reliability"
    type: percentile
    percentile: 90
    sql: ${total_ms} ;;
    description: "90th percentile latency for LLM responses in milliseconds."
  }
  
  measure: p99_llm_latency {
    group_label: "Performance & Reliability"
    type: percentile
    percentile: 99
    sql: ${total_ms} ;;
    description: "99th percentile latency for LLM responses in milliseconds."
  }

  # --- POP MEASURES: TOTAL TOKENS ---

  measure: pop_total_tokens_current {
    group_label: "PoP: Total Tokens Consumed"
    type: sum
    sql: ${usage_total_tokens} ;;
    filters: [agent_events.is_current_period: "yes"]
    description: "Total tokens consumed in the currently selected PoP date range."
  }

  measure: pop_total_tokens_previous {
    group_label: "PoP: Total Tokens Consumed"
    type: sum
    sql: ${usage_total_tokens} ;;
    filters: [agent_events.is_previous_period: "yes"]
    description: "Total tokens consumed in the previous period of the exact same length."
  }

  measure: pop_total_tokens_change {
    group_label: "PoP: Total Tokens Consumed"
    type: number
    value_format_name: percent_2
    sql: SAFE_DIVIDE(${pop_total_tokens_current} - ${pop_total_tokens_previous}, ${pop_total_tokens_previous}) ;;
    description: "The percentage change in total tokens between the current and previous period."
  }

  # --- POP MEASURES: PROMPT TOKENS ---

  measure: pop_prompt_tokens_current {
    group_label: "PoP: Prompt Tokens"
    type: sum
    sql: ${usage_prompt_tokens} ;;
    filters: [agent_events.is_current_period: "yes"]
    description: "Total prompt tokens consumed in the currently selected PoP date range."
  }

  measure: pop_prompt_tokens_previous {
    group_label: "PoP: Prompt Tokens"
    type: sum
    sql: ${usage_prompt_tokens} ;;
    filters: [agent_events.is_previous_period: "yes"]
    description: "Total prompt tokens consumed in the previous period."
  }

  measure: pop_prompt_tokens_change {
    group_label: "PoP: Prompt Tokens"
    type: number
    value_format_name: percent_2
    sql: SAFE_DIVIDE(${pop_prompt_tokens_current} - ${pop_prompt_tokens_previous}, ${pop_prompt_tokens_previous}) ;;
    description: "The percentage change in prompt tokens between the current and previous period."
  }

  # --- POP MEASURES: COMPLETION TOKENS ---

  measure: pop_completion_tokens_current {
    group_label: "PoP: Completion Tokens"
    type: sum
    sql: ${usage_completion_tokens} ;;
    filters: [agent_events.is_current_period: "yes"]
    description: "Total completion tokens generated in the currently selected PoP date range."
  }

  measure: pop_completion_tokens_previous {
    group_label: "PoP: Completion Tokens"
    type: sum
    sql: ${usage_completion_tokens} ;;
    filters: [agent_events.is_previous_period: "yes"]
    description: "Total completion tokens generated in the previous period."
  }

  measure: pop_completion_tokens_change {
    group_label: "PoP: Completion Tokens"
    type: number
    value_format_name: percent_2
    sql: SAFE_DIVIDE(${pop_completion_tokens_current} - ${pop_completion_tokens_previous}, ${pop_completion_tokens_previous}) ;;
    description: "The percentage change in completion tokens between the current and previous period."
  }

  # --- POP MEASURES: LLM CALLS ---

  measure: pop_llm_calls_current {
    group_label: "PoP: LLM Calls"
    type: count
    filters: [agent_events.is_current_period: "yes"]
    description: "Total LLM calls in the currently selected PoP date range."
  }

  measure: pop_llm_calls_previous {
    group_label: "PoP: LLM Calls"
    type: count
    filters: [agent_events.is_previous_period: "yes"]
    description: "Total LLM calls in the previous period."
  }

  measure: pop_llm_calls_change {
    group_label: "PoP: LLM Calls"
    type: number
    value_format_name: percent_2
    sql: SAFE_DIVIDE(${pop_llm_calls_current} - ${pop_llm_calls_previous}, ${pop_llm_calls_previous}) ;;
    description: "The percentage change in LLM calls between the current and previous period."
  }

}