include: "/views/raw/v_llm_response.view.lkml"

view: +v_llm_response {
  sql_table_name: `@{PROJECT_ID}.@{DATASET_NAME}.v_llm_response` ;;

  dimension: pk {
    primary_key: yes
    hidden: yes
    type: string
    sql: CONCAT(${trace_id}, '|', ${span_id}) ;;
    description: "Internal composite primary key for symmetric aggregates."
  }

  dimension: usage_total_tokens {
    group_label: "Token Usage"
    description: "The total number of tokens (prompt + completion) consumed by this specific LLM response."
  }

  dimension: usage_prompt_tokens {
    group_label: "Token Usage"
    description: "The number of tokens consumed by the input prompt sent to the LLM."
  }

  dimension: usage_completion_tokens {
    group_label: "Token Usage"
    description: "The number of tokens consumed by the output generated by the LLM."
  }

  dimension: usage_cached_tokens {
    group_label: "Token Usage"
    description: "The number of prompt tokens that were served from the context cache, reducing latency and cost."
  }

  dimension: context_cache_hit_rate {
    group_label: "Token Usage"
    description: "The percentage of the prompt that was served from the cache (cached tokens / total prompt tokens)."
  }

  dimension: total_ms {
    group_label: "Latency"
    description: "The total wall-clock time in milliseconds the LLM took to process the request and generate the full response."
  }

  dimension: ttft_ms {
    group_label: "Latency"
    description: "Time To First Token (TTFT). The latency in milliseconds before the LLM began streaming the first token of the response."
  }

  dimension: model_version {
    group_label: "Event Info"
    description: "The specific version of the LLM model used for this request (e.g., 'gemini-2.5-flash')."
  }

  measure: total_tokens_consumed {
    group_label: "Usage & Volume"
    type: sum
    sql: ${usage_total_tokens} ;;
    description: "Total tokens consumed across all LLM responses in the selected timeframe."
  }

  measure: total_prompt_tokens {
    group_label: "Usage & Volume"
    type: sum
    sql: ${usage_prompt_tokens} ;;
    description: "Total prompt tokens consumed across all LLM responses."
  }

  measure: total_completion_tokens {
    group_label: "Usage & Volume"
    type: sum
    sql: ${usage_completion_tokens} ;;
    description: "Total completion (candidate) tokens generated across all LLM responses."
  }

  measure: total_llm_calls {
    group_label: "Usage & Volume"
    type: count
    description: "Total number of successful LLM responses."
  }

  measure: p50_llm_latency {
    group_label: "Performance & Reliability"
    type: percentile
    percentile: 50
    sql: ${total_ms} ;;
    description: "Median (P50) latency for LLM responses in milliseconds."
  }

  measure: p90_llm_latency {
    group_label: "Performance & Reliability"
    type: percentile
    percentile: 90
    sql: ${total_ms} ;;
    description: "90th percentile latency for LLM responses in milliseconds."
  }
  
  measure: p99_llm_latency {
    group_label: "Performance & Reliability"
    type: percentile
    percentile: 99
    sql: ${total_ms} ;;
    description: "99th percentile latency for LLM responses in milliseconds."
  }

}